"""add release_date to Games

Revision ID: 00c4062d0604
Revises: 1322d1cd8eb8
Create Date: 2023-08-16 12:37:05.134637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c4062d0604'
down_revision = '1322d1cd8eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
