"""fix schema genre id

Revision ID: 031ecb4bdd7d
Revises: e056c1fddbfa
Create Date: 2023-08-22 06:07:45.088743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031ecb4bdd7d'
down_revision: Union[str, None] = 'e056c1fddbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
