"""update Game

Revision ID: 091daa67a8bc
Revises: 2c7f63974f2d
Create Date: 2023-08-16 12:29:16.527910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091daa67a8bc'
down_revision = '2c7f63974f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
