"""update Game

Revision ID: 1322d1cd8eb8
Revises: 091daa67a8bc
Create Date: 2023-08-16 12:34:40.402248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1322d1cd8eb8'
down_revision = '091daa67a8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
