"""create genres

Revision ID: 198b14472e5e
Revises: 
Create Date: 2023-08-15 08:13:42.503843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198b14472e5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    # ### end Alembic commands ###
