"""change m2m to game platform 1.3

Revision ID: 2901c258f7cf
Revises: c0b468a4fb27
Create Date: 2023-08-22 21:08:23.517366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2901c258f7cf'
down_revision: Union[str, None] = 'c0b468a4fb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
