"""update Game

Revision ID: 2c7f63974f2d
Revises: 91049bf0c2f4
Create Date: 2023-08-16 12:25:29.734373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7f63974f2d'
down_revision = '91049bf0c2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
