"""remove release date

Revision ID: 370ee57b2df6
Revises: 00c4062d0604
Create Date: 2023-08-16 12:38:05.042666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370ee57b2df6'
down_revision = '00c4062d0604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('release_date', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
