"""remove secondary from GAme

Revision ID: 4ad208d8a0d8
Revises: 68b428d61c5f
Create Date: 2023-08-22 08:15:43.689430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad208d8a0d8'
down_revision: Union[str, None] = '68b428d61c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
