"""add genre_type and platform_name Column

Revision ID: 4cf6f5a9abf7
Revises: 55f7b9de5595
Create Date: 2023-08-22 21:24:26.873367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf6f5a9abf7'
down_revision: Union[str, None] = '55f7b9de5595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
