"""change m2m to game platform 1.4

Revision ID: 55f7b9de5595
Revises: 2901c258f7cf
Create Date: 2023-08-22 21:09:53.462015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f7b9de5595'
down_revision: Union[str, None] = '2901c258f7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
