"""update Game

Revision ID: 5ccca7d3f582
Revises: ff4e234c5c95
Create Date: 2023-08-16 10:35:47.498630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccca7d3f582'
down_revision = 'ff4e234c5c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
