"""fix schema ids for Game 1.3

Revision ID: 7987cc59589e
Revises: 3e739aee5775
Create Date: 2023-08-22 06:18:59.595071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7987cc59589e'
down_revision: Union[str, None] = '3e739aee5775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
