"""update Game

Revision ID: 79f91d422997
Revises: e3360152a133
Create Date: 2023-08-16 12:13:56.354874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f91d422997'
down_revision = 'e3360152a133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('release_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'release_date')
    # ### end Alembic commands ###
