"""update Game

Revision ID: 91049bf0c2f4
Revises: 79f91d422997
Create Date: 2023-08-16 12:24:55.825571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91049bf0c2f4'
down_revision = '79f91d422997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
