"""fix schema ids for Game 1.5

Revision ID: 9b1b2ac3aea3
Revises: eb1576e616c6
Create Date: 2023-08-22 07:00:09.186213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1b2ac3aea3'
down_revision: Union[str, None] = 'eb1576e616c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
