"""update models

Revision ID: b2615137aa94
Revises: be2e52a6f0fd
Create Date: 2023-08-16 09:44:50.078675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2615137aa94'
down_revision = 'be2e52a6f0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('esrb_rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'esrb_rating')
    # ### end Alembic commands ###
