"""update genres and create platforms

Revision ID: d8663221197a
Revises: 198b14472e5e
Create Date: 2023-08-15 08:37:24.991693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8663221197a'
down_revision = '198b14472e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('genres', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('genres', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.drop_column('genres', 'type')
    op.drop_table('platforms')
    # ### end Alembic commands ###
