"""fix schema genre id 1.2

Revision ID: dfbeea8e4b31
Revises: 031ecb4bdd7d
Create Date: 2023-08-22 06:10:13.457418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbeea8e4b31'
down_revision: Union[str, None] = '031ecb4bdd7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
