"""update Game

Revision ID: e3360152a133
Revises: 5ccca7d3f582
Create Date: 2023-08-16 10:43:43.263404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3360152a133'
down_revision = '5ccca7d3f582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
