"""fix schema ids for Game 1.0

Revision ID: f8ba895bf52d
Revises: d8f63741a04d
Create Date: 2023-08-22 06:14:15.396617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ba895bf52d'
down_revision: Union[str, None] = 'd8f63741a04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
