"""update Game

Revision ID: ff4e234c5c95
Revises: b2615137aa94
Create Date: 2023-08-16 10:33:09.774532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4e234c5c95'
down_revision = 'b2615137aa94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
